services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalogdb
    restart: always
    ports: 
        - "5432:5432"
    volumes:
    - postgres_catalog:/var/lib/postgresql/18/docker

  catalog.api:
    container_name: catalog.api
    ports:
      - "8080:8080"
      - "8081:8081"